### ISSUE TITLE
Support running servers under another user

### ISSUE THREAD

**Issue by BotoX** [riemers/wrench#1]
The functionality provided by this script is really great and it probably is the best tool to manage srcds installs.
However the fact that all the servers have to run as the same user is very unfortunate.
My setup consists of multiple servers for the same game which are managed by different people, they should only have access to the servers they manage.
This can only be done **properly** if these servers run under different users, as far as I am aware.

You've mentioned steamcmd not supporting multiple users, would this be a problem for providing this functionality?
I made a few things in bash before, but 4800 lines is a bit too much for me to jump at this without any background info.
Right now I am running the script under multiple users which renders most of it's advantages useless.

**Comment by riemers** [comment]
Adding features like that in its current situation is too much. If you have different users, you still need to communicate this to your central database, in this case sqlite. That means that all your users need access to it.

You could instead try a different approach. You could add multiple users with the same uid. Then give everyone access to their particular srcds/<servername>. Only allow "ftp" to it, then disable ssh and let them not be able to "walk down" the path to the main server part. Then users can still manage their own files but wont be able to adjust any "shared" files since they don't have rights to those files.

Perhaps something like that could work? In reality you could change sqlite with mysql or mongo or whatever but that requires rights to the database at some point and as long as you give them ssh access they will know those details too.

**Comment by BotoX** [comment]
Ah, I see what you mean with the database problem, however wouldn't it be possible to put the script on it's own user with sudo rights to the users in the gameserver group, like:
`wrench ALL = (%servers) NOPASSWD: ALL`
so the script parts will run as the wrench user and the gameservers will each have their own user that's in the servers group.

I didn't actually know that you could re-use the same uid, that's definitely a solution I could try but it still has the same security risks of the users accessing the other servers. They can upload a malicious extension which'd give them shell access to the server through a remote shell (I actually did this before).
And sometimes you also want to give your users shell access but not let them fiddle with other users servers.

**Comment by riemers** [comment]
Wrench uses certain chmods and a user cannot edit those files unless they change the rights. I don't know if its possible to use that same method to remove people the ability to upload bad extensions/mods. (by setting the folder to read only) as an example you can (as root) set a file to chattr +i <filename> and even when "root" does a "rm <filename>" it will get a denied request. Only when you chattr -i the file can you do stuff again with it. In a similar way, multiple accounts with the same uid and in their own chroot folder to only their instance + ownership changes so they cannot upload would fix some issues you have.

Then again, you can always upload a file somewhere else and run a add plugin from an .cfg that you uploaded. I would know more ways to break out then keep them out. Either you chroot them completely, so they can only screw up their instance and nothing else or look for other alternatives.

Never tried using docker for gameservers, but that will stop them from screwin around but then wrench wont work with that sadly. Needs a rewrite too. However you pull it off, there will always be a way for them to screw around. Either trust your admins, or assume the box can be nuked and restored quickly.

**Comment by BotoX** [comment]
I followed your suggestion and did the following:
- Create user "servers" and group "servers"
- Create users "server_name" with same uid as "servers" and primary group "servers"
- User "servers" has a valid login shell and can use wrench through SSH
- The other users, eg. "server_name" have no valid login shell and can only access the server files through chrooted vsftpd (home directory set to /home/servers/srcds/css-name)

Malicious extensions that give the user shell access can circumvent that, so I guess I'll leave this issue open.
Maybe I'll get around writing my own script (in python) to solve this, someday...

**Comment by riemers** [comment]
Or don't allow them to upload new mods/plugins, but i think that would defeat the purpose you where trying to achieve.

**Comment by riemers** [comment]
Since you 'might' have your own ways, i'll be closing this one then. Perhaps you can make a Pull request in the future, we never know ;)
